<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Customer_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>35bf4f01-08d6-4941-ad2d-865bf799c083</testSuiteGuid>
   <testCaseLink>
      <guid>662c6e89-6c7b-4161-b11e-1a2ff493556c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Email address and password cannot be blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f26ff41-5166-478e-8a8f-d292288cbdcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1322238b-12f4-47f8-bbff-e0ca63c00937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27e494fb-de50-4c57-94e0-f8c599f072a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d49c0a3-c01d-472f-b373-a712368dcd87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Email address format</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cdecf5a-13d0-4859-a0c6-4cc153ed2acd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e5d7850-7495-4fbb-bbce-e815e2f74362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8a4695f-61af-4f35-b5b4-108dee2ecf2e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d605776-2548-41de-a74b-1e2b8bc7f94e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Email address exists in customer table database</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb042905-931c-48e1-8711-81b2993728a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb661c3e-e3ec-4256-b655-05dd9550bbb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eec7586c-164f-498b-a25d-5b6ae6d559f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7610764e-8134-4e61-ac22-b38794466ca8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Email address does not exist in the database</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac34b12-4bbc-4f11-90ef-7510c0cefae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4e7da0d-8c80-45c5-bdef-124591b940f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1865150-0c64-4511-906d-bdd5707d9dc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82ea1f3c-3652-4720-9444-7e681e0df4ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Incorrect email address, correct password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1975096-1bc4-4c8f-98f0-e263b790eab7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76b265a6-5b48-4be3-9823-87550a3655c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb472fda-ea60-4610-9b3c-4ae393198c3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0e69802-d736-43b7-b89c-c2a140e2d6ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Email address correct, password incorrect</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22eacd34-c511-4c7a-ae75-3cef7a4e76cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caafbba5-e803-4e5b-9733-88a8bfc2744c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4e0d84-b8fd-4947-90f7-5444c223970a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37bccb0a-b839-4949-9a8b-fcba5504a0c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Customer Login/CL_Login successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04b5e27f-d57c-42dc-9579-b16eea511be0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bac289b3-89aa-4887-b6a0-0057bb4847d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff78ef4f-eda3-4bd7-bd6a-9c3c45997bbb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
