<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Payment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>27841e5d-ff0e-4954-8b8d-58a0087d1a80</testSuiteGuid>
   <testCaseLink>
      <guid>c10ad0af-a406-4303-85c4-24747218c26d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Verify login account before payment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f6ac88b1-05ac-4547-b3d9-d83648c98fe7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Confirm after user login, redirect back to payment page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e802fa8-2325-4931-8fc1-95769f0dbf47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cc67b36-1bf7-4040-9d18-46e062b54bc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9e85bc3-cd5c-403c-90c5-b9fc88f92ed8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c5f5cb1-2c9a-4123-91d1-54020cb284e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check that the ordered product information is displayed correctly</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfbfb5db-66ca-42a8-975b-a59682b13399</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d84cea7-f041-4d20-b050-3d46ab6f658e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e489bef0-46e6-4533-ad64-1fef500ae081</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d77c585-d859-41cb-89ac-be2aff9f6adb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check final order value calculation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7227197c-53e1-45cf-aa68-8570da88be67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92503038-6e5b-4dee-9eb2-c45de8777ec5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20d241c-c73f-4696-b891-16607cd2b00f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2befb41-036c-4e12-a5b6-82e15c096ae4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check Billing Address and Shipping Address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d30c9506-e566-4609-bf08-0b343972949f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12ab611-533a-4ff2-85fe-ae6f0892b9c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59aa7cb6-0aa0-40a4-9fb8-c6ccd8901d3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa352a68-6730-44aa-9cdb-46f885d6780e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check that the Back to Cart button is working</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e3922b6-7614-41ac-b194-3c43ed587215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ae2cb1a-1da7-4a7f-8db1-e76157d38910</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fd36a05-4b6e-4818-9614-2ab6a74ed568</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87206a68-3a52-428c-837b-83d5d41a6899</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check that the Paypal Checkout button is working</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d27c9606-8a50-405f-904b-63824d4414ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b11607c0-c461-44e5-8ba4-53dffe13ba09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d735af6e-76a5-4855-b61a-a77d9b1498d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e0faa20-134d-4227-8dac-8643ba83c23e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Payment/PM_Check the operation of the QR MoMo Payment button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7386466-1e81-4fba-92bd-ea0fdca39a1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5cbdebe-60ee-4f2f-911f-6026d1f9c160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ae8521-aa8d-4f67-82a4-3cc4b967f15c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
